version: "3.9"

services:
  pd_web:
    build:
      dockerfile: Dockerfile
    image: pd_web:latest
    restart: always
    container_name: pd_web
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/app/configs
      - ./routers:/app/routers
      - ./static:/app/static
    networks:
      webservicepd_pd_web_net:
        aliases:
          - pd_web

networks:
  webservicepd_pd_web_net:
    driver: bridge
